//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class intervento
    {
        public string IdReferto { get; set; }
        public string Giorno { get; set; }
        public string OraInizio { get; set; }
        public string OraFine { get; set; }
        public string IdIntervento { get; set; }
        public string Descrizione { get; set; }
        public string IdPaziente { get; set; }
    }
}
